-- Criar o banco de dados
CREATE DATABASE IF NOT EXISTS planbasedb;

-- Usar o banco de dados
USE planbasedb;

-- Tabela FUNCIONARIO_CADASTRADO
CREATE TABLE IF NOT EXISTS FUNCIONARIO_CADASTRADO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    MATRICULA VARCHAR(10) NOT NULL UNIQUE,
    CARGO VARCHAR(255),
    DATA_INICIO DATE,
    SENHA VARCHAR(255) NOT NULL,
    CONFIRMAR_SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NASCIMENTO DATE,
    TELEFONE VARCHAR(20),
    CIDADE VARCHAR(255),
    UF VARCHAR(2),
    PAIS VARCHAR(255)
);

-- Tabela LOGIN_ADM
CREATE TABLE IF NOT EXISTS LOGIN_ADM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA VARCHAR(10) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL
);

-- Tabela LOGIN_FUNCIONARIO
CREATE TABLE IF NOT EXISTS LOGIN_FUNCIONARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA VARCHAR(10) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL
);

-- Tabela ENTRADA
CREATE TABLE IF NOT EXISTS ENTRADA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255),
    CATEGORIA VARCHAR(255),
    DATA_REGISTRO DATE,
    VALOR DECIMAL(10, 2),
    HISTORICO TEXT,
    STATUS_ENTRADA VARCHAR(50),
    FORNECEDOR VARCHAR(255),
    DESTINATARIO VARCHAR(255),
    NOTA_FISCAL VARCHAR(50),
    PAGAMENTO varchar(255),
    QTD_PARCELA INT
);

-- Tabela SAIDA
CREATE TABLE IF NOT EXISTS SAIDA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255),
    CATEGORIA VARCHAR(255),
    DATA_REGISTRO DATE,
    VALOR DECIMAL(10, 2),
    HISTORICO TEXT,
    STATUS_SAIDA VARCHAR(50),
    FORNECEDOR VARCHAR(255),
    DESTINATARIO VARCHAR(255),
    NOTA_FISCAL VARCHAR(50),
    PAGAMENTO varchar(255),
    QTD_PARCELA INT
);

-- Tabela PREVISOES
CREATE TABLE IF NOT EXISTS PREVISOES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255),
    CATEGORIA VARCHAR(255),
    DATA_REGISTRO DATE,
    VALOR DECIMAL(10, 2),
    HISTORICO TEXT,
    NOTA_FISCAL VARCHAR(50),
    PAGAMENTO DATE,
    QTD_PARCELA INT
);

-- Tabela CAIXA
CREATE TABLE IF NOT EXISTS CAIXA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255),
    CATEGORIA VARCHAR(255),
    DATA_REGISTRO DATE,
    VALOR DECIMAL(10, 2),
    HISTORICO TEXT,
    NOTA_FISCAL VARCHAR(50),
    PAGAMENTO DATE,
    QTD_PARCELA INT
);

-- Tabela CARTOES
CREATE TABLE IF NOT EXISTS CARTOES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AGENCIA VARCHAR(20),
    CONTA VARCHAR(20),
    INSTITUICAO_BANCARIA VARCHAR(255),
    ICON_INSTITUICAO_BANCARIA VARCHAR(255),
    TAXA DECIMAL(5, 2),
    TIPO_COBRANCA VARCHAR(50)
);

-- Tabela FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_EMPRESA VARCHAR(255),
    TIPO_CONTRATO VARCHAR(50),
    CONTATO_EMPRESARIAL VARCHAR(255),
    VALOR_CONTRATO DECIMAL(10, 2)
);
